name: "Maven"
description: "Action used to build projects using Maven"
inputs:
  service_account_key:
    description: "gcloud auth service_account_key"
    required: true
#  gcr_name:
#    description: "repository name of gcr"
#    required: true



env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_REPOSITORY: ${{ github.repository }}



runs:
  using: "composite"
  steps:
    - name: Set up gcloud
      id: gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '278.0.0'
        service_account_key: ${{ inputs.service_account_key }}
