---
name: 'CICD'

on:
  push:

env:
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  PUSH_TYPE: $(printf '%s' "$GITHUB_BRANCH" | cut -f2 -d/)
  IMAGE_TAG: ${PREFIX}"-"$(printf '%s' "$GITHUB_SHA" | cut -c 1-7)
  IMAGE_NAME: $(printf '%s' "$GITHUB_REPOSITORY" | cut -f2- -d/)
  PROJECT_NAME: "chess-gcr1"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building and Pushing the image
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Composite-action

      - id: docker-build-push
        if: ${{ github.ref }} == 'refs/heads/staging'
        run: echo ${{ github.ref }}

      - name: Does this run
        if: ${{ env.GITHUB_BRANCH }} == 'refs/heads/master'
        run: pwd
  push:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v3