---
name: 'CICD'

on:
  push:


env:
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  PUSH_TYPE: $(printf '%s' "$GITHUB_BRANCH" | cut -f2 -d/)
  IMAGE_TAG: ${PREFIX}"-"$(printf '%s' "$GITHUB_SHA" | cut -c 1-7)
  IMAGE_NAME: $(printf '%s' "$GITHUB_REPOSITORY" | cut -f2- -d/)
  PROJECT_NAME: "chess-gcr1"
  CHESSCOM_GCR: gcr.io/chess-gcr1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building and Pushing the image
    steps:
      - uses: actions/checkout@v3
      - name: Display Key Run Params
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          SHORT_SHA=${GITHUB_SHA::7}
          echo ${{ steps.run_params.outputs.img-tag }}
          echo ${{ steps.run_params.outputs.img-name }}
          IMG_TAG=$BRANCH-$SHORT_SHA
          echo $IMG_TAG >> $GITHUB_ENV

      - name: Print github_env
        run: |
          echo $IMG_TAG
#      outputs:
#        image_tag: ${{ steps.run_params.outputs.img-tag }}
#        image_name: ${{ steps.run_params.outputs.img-name }}
#      - id: docker-build-push
#        uses: ./.github/actions/docker-build
#        with:
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          gcr_name: chess-gcr1
#          image_tag: ${{ steps.run_params.outputs.img-tag }}
#          image_name: ${{ steps.run_params.outputs.img-name }}